language: rust

jobs:
  include:
    - stage: check
      os: linux
      dist: xenial
      rust: stable
      before_script:
        - rustup component add rustfmt clippy
      script:
        - cargo clippy --all --manifest-path ./Cargo.toml -- --deny warnings
        - cargo clippy --all --manifest-path ./testdata/simple/Cargo.toml -- --deny warnings
        - cargo clippy --all --manifest-path ./testdata/workspace/Cargo.toml -- --deny warnings
        - (cd . && cargo fmt --all -- --check)
        - (cd ./testdata/simple && cargo fmt --all -- --check)
        - (cd ./testdata/workspace && cargo fmt --all -- --check)
    - stage: test
      os: osx
      osx_image: xcode10.1
      addons:
        homebrew:
          packages:
            - bats-core
      rust:
        - stable
        - 1.28.0
        - beta
        - nightly
      script: ./deploy
